version: '3.8'
services:
  netguru-db:
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: netguru
      MYSQL_USER: netguru
      MYSQL_PASSWORD: netguru!R4ndomS3cure
      MYSQL_ROOT_PASSWORD: netguru!R4ndomS3cure

  netguru-api:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
    - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - netguru-db
    stdin_open: true
    tty: true
    environment:
      DB_HOST: netguru-db
      DB_PORT: 3306
      DB_NAME: netguru
      DB_USER: netguru
      DB_PASSWORD: netguru!R4ndomS3cure
      JWT_SECRET: ${JWT_SECRET}
