name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: up mysql
      run: docker-compose up -d netguru-test-db
    - run: npm ci
    - run: npx mikro-orm migration:create --initial
    - run: npm test
